In [1]:
# importing modul we will use
import numpy as np
import scipy.linalg as ls
import sympy as sp
sp.init_printing()

In [2]:
# making one dimension list which content number from 1 to 9 then it reshaping that list to be two dimensianal list
# or matrix
A = np.array([i for i in range(1, 10)]).reshape(3,3)

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# making identity matrix
T = np.eye(3)

In [5]:
T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# mengganti elemen tertentu dalam matriks identitas
# matriks ini yang akan digunakan untuk dikalikan dengan matriks target yang akan ditukar posisi baris
T[1,1] = 0
T[2,2] = 0
T[1,2] = 1
T[2,1] = 1
T

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **OPERASI MENUKAR BARIS**
###### **MENGALIKAN MATRIX T DENGAN MATRIX A**
 - pengaturan angka satu dalam matrix yang akan menukar posisi baris ini mewakili
 - misal baris pertama di matrix T = 1 | 0 | 0
 - maksudnya adalah di hasil akhir nanti jika matrix ini dikalikan dengan matrix A, akan membuat baris pertama matrix A menjadi hasil di baris pertama
 - baris kedua di matrix T = 0 | 0 | 1
 - hasil di akhir perkalian antara matrix T dan A nanti akan menjadikan baris ke 3 matrix A menjadi baris kedua
 di matrix hasilnya
 - baris ketiga di matrix T = 0 | 1 | 0
 - hasil akhir perkalian antara matrix T dan A nanti akan menjadikan baris ke 2 matrix A menjadi baris ke 3
 di matrix hasilnya

In [8]:
# mengalikan matriks T dan A untuk mendapatkan matriks yang barisnya telah ditukar
T@A

array([[1., 2., 3.],
       [7., 8., 9.],
       [4., 5., 6.]])

### **OPERASI MENUKAR KOLOM**
#### **MENGALIKAN MATRIX A DENGAN MATRIX T**

- pengaturan angka satu dalam matrix yang akan menukar posisi kolom ini mewakili
- misal kolom pertama di matrix T itu 1 | 0 | 0
- maksudnya adalah di hasil akhir nanti jika matrix A dikalikan dengan matrix T, akan membuat kolom pertama matrix A menjadi
  hasil di kolom pertama matrix hasil

- kolom kedua di matrix T = 0 | 0 | 1
- hasil di akhir perkalian matrix A dan matrix T nanti akan menjadikan kolom ke 3 matrix A menjadi kolom ke 2 di matrix hasil

- kolom ketiga di matrix T = 0 | 1 | 0
- hasil di akhir perkalian matrix A dan matrix T nanti akan menjadikan kolom ke 2 matrix A menjadi kolom ke 3 di matrix hasil


In [9]:
print(A)
print()
print(T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [10]:
# matriks A yang kolomnya akan ditukar posisikan dikalikan dengan matriks identitas
A@T

array([[1., 3., 2.],
       [4., 6., 5.],
       [7., 9., 8.]])

In [11]:
# mengecek ordo matriks
print('Ordo dari matrix A =', A.shape)

Ordo dari matrix A = (3, 3)


In [12]:
# definisikan fungsi modifikasi dari ref 1
# menukar baris i dengan baris j

def swap_row(A, i, j):
    """Fungsi ini menukar posisi antar baris misal baris kesatu dan kedua

    Args:
        A (array): matriks atau array 2d
        i (int): baris ke i
        j (int): baris ke j

    Returns:
        matriks : array 2d
    """
    n = A.shape[0]      # menyimpan jumlah baris matriks dari ordonya

    E = np.eye(n)       # membuat matrix identitas dengan n ordo matrix
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1

    return E@A  # operasi pemindahan baris mengalikan matrix identitas dengan matrix target

In [13]:
n = A.shape[0]
E = np.zeros((3,3))
E

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# pemanggilan fungsi untuk menukar baris kedua menjadi baris ketiga dan baris ketiga menjadi kedua pada matriks A
swap_row(A, 1, 2)

array([[1., 2., 3.],
       [7., 8., 9.],
       [4., 5., 6.]])

### **Fungsi yang mengambil row dari matriks untuk operasi**

In [15]:
# buat matrix yang berisi baris i dari matrix A ditempatkan pada baris j
def get_row(A, i, j):
    """fungsi ini akan membuat matriks nol dan menyisipkan angka 1 di elemen[j,i] dan mengalikannya dengan matriks target
        sehingga diperoleh satu baris saja dalam matriks hasilnya baris lainnya punya nilai nol semua.

    Args:
        A (array): array target
        i (int): baris asal matriks target (yang akan digunakan sebagai pengurang / penjumlah)
        j (int): baris tujuan di matriks hasil (baris yang akan mengurangi / menjumlah baris di matriks target)

    Returns:
        matriks : array 2d
    """

    n = A.shape[0]          # menyimpan jumlah baris matriks dari ordonya
    E = np.zeros((n,n))     # membuat matriks nol
    E[j,i] = 1              # mengganti elemen matriks baris ke j dan kolom ke i dengan satu
    return E@A              # mengalikan matriks E dengan matriks A untuk mendapatkan matriks yang hanya punya satu baris
                            # yang digunakan untuk mengurangi atau menjumlah

In [16]:
# pemanggilan fungsi untuk mendapatkan matriks yang baris ke tiga nya adalah baris ke dua dati matriks A
get_row(A, 1, 2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [4., 5., 6.]])

#### **Fungsi Yang Menskalakan Matriks**

In [17]:
# kalikan skala s pada baris i dari matriks A

def scale_row(A, i, s):
    """fungsi ini akan membuat mariks identitas kemudian mengisi elemen [i,i] nya dengan angka perkalian skalanya mengalikannya
        dengan matriks target

    Args:
        A (array): Matriks target
        i (int): baris ke berapa pada matriks target yang akan di skalakan atau dijadikan sebagai pengurang atau penjumlah
        s (int): dikali dengan berapa

    Returns:
        matriks : array 2d
    """
    n = A.shape[0]          # menyimpan baris matriks dari ordonya
    E = np.eye(n)           # membuat matriks non
    # mengubah elemen matriks E pada baris ke i dan kolom ke i menjadi nol
    E[i, i] = s
    # mengalikan matriks E dan matriks A untuk mendapatkan matriks yang suatu barisnya sudah dikalikan
    return E@A
    # dengan suatu bilangan


In [18]:
# menukar baris kedua dengan baris ketiga
swap_row(A, 1, 2)

array([[1., 2., 3.],
       [7., 8., 9.],
       [4., 5., 6.]])

In [19]:
# panggil fungsi untuk mendapatkan matriks yang meyimpan baris kesatu matriks A di baris ketiga
get_row(A, 0, 2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [20]:
# panggil fungsi untuk mengalikan baris kesatu matriks dengan 3
scale_row(A, 0, 3)

array([[3., 6., 9.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### **Soal 1 dengan metode eliminasi Gauss dan substitusi kembali**

$x+y+z=1$

$x+2y+4z=-1$

$x+3y+9z=1$

In [21]:
# mengetikan koefisien-koefisien dari baris di sistem persamaan linear dalam list 2 dimensi
# kemudian mengubah tipe datanya menjadi array 2d
# matriks a itu ruas kiri persamaan linear
# matriks b itu ruas kanan persamaan linear

a = np.array([[1,1,1], [1,2,4],[1,3,9]])
b = np.array([[1,-1,1]])

In [22]:
# menyisipkan array b ke dalam kolom array a
a = np.insert(a, 3, b, axis=1)
a

array([[ 1,  1,  1,  1],
       [ 1,  2,  4, -1],
       [ 1,  3,  9,  1]])

In [23]:
# b2 - b1
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasil tersebut adalah matriks nol yang baris keduanya merupakan baris kesatu matriks a
a = a - get_row(a, 0, 1)
print(a)

[[ 1.  1.  1.  1.]
 [ 0.  1.  3. -2.]
 [ 1.  3.  9.  1.]]


In [24]:
# b3 - b1
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol baris ke 3 adalah baris ke 1 baris a
a = a - get_row(a, 0, 2)
print(a)

[[ 1.  1.  1.  1.]
 [ 0.  1.  3. -2.]
 [ 0.  2.  8.  0.]]


In [25]:
# b3 - 2 b2
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 3 nya adalah 2 kali dari baris ke 2 baris a
a = a - 2 * get_row(a, 1, 2)
print(a)

[[ 1.  1.  1.  1.]
 [ 0.  1.  3. -2.]
 [ 0.  0.  2.  4.]]


In [26]:
# 1/2 b3
# mengalikan baris ke 3 matriks a dengan 1/2
a = scale_row(a, 2, 1/2)
print(a)

[[ 1.  1.  1.  1.]
 [ 0.  1.  3. -2.]
 [ 0.  0.  1.  2.]]


In [27]:
# b2 - 3 b3
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 2 nya adalah 3 kali dari baris ke 3 baris a
a = a - 3*get_row(a, 2, 1)
print(a)

[[ 1.  1.  1.  1.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1.  2.]]


In [28]:
# b1 - b2
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 1 nya adalah baris ke 2 matriks a
a = a - get_row(a, 1, 0)
print(a)

[[ 1.  0.  1.  9.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1.  2.]]


In [29]:
# b1 - b3
# mengurangi matriks a dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 1 nya adalah baris ke 3 matriks a
a = a - get_row(a, 2, 0)
print(a)

[[ 1.  0.  0.  7.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1.  2.]]


In [30]:
print("Matriks hasilnya adalah")
print(a)

Matriks hasilnya adalah
[[ 1.  0.  0.  7.]
 [ 0.  1.  0. -8.]
 [ 0.  0.  1.  2.]]


**bila di ubah ke persamaan linear kembali didapat nilai-nilai dari variabelnya sebagai berikut:**
- x = 7
- y = -8
- z = 2

### **Soal 2 dengan metode GAUSS-SEIDEL**

$2x+y+z=2$

$x+4y+2z=1$

$x+3y+9z$

#### **Bentuk kodingan 1**

In [31]:
tol = 1.0E-10       # toleransi error
delta = 1000        # akan menghentikan while loop jika nilainya lebih kecil dari toleransi error atau epsilon

# nilai awal variabel x, y, z
xn = 0
yn = 0
zn = 0
n = 0

# loop ketika delta > toleransi errornya
while delta > tol:
    n += 1                              # n = n + 1

    # xn + 1 = F(xn)
    # sistem persamaan linear
    xnp1 = (1/2) * (2 - yn - zn)
    ynp1 = (1/4) * (1 - xnp1 - 2*zn)
    znp1 = (1/9) * (1 - xnp1 - 3*ynp1)

    # mencari galat dari nilai masing-masing variabel
    delta = abs(xnp1 - xn) + abs(ynp1 - yn) + abs(znp1 - zn)

    # menyimpan nilai variabel yang baru dihitung
    xn = xnp1
    yn = ynp1
    zn = znp1

print([xn, yn, zn])

[1.0, 0.0, 0.0]


In [32]:
# nilai dari masing-masing variabel nya
print(f"x = {xn}")
print(f"y = {yn}")
print(f"z = {zn}")

x = 1.0
y = 0.0
z = 0.0


### **Bentuk kodingan 2**
#### **Scipy.linalg**


In [33]:
# menngetikan koefisien-koefisien sistem persamaan linear dalam list 2d
# kemudian mengubahnya tipe datanya menjadi array 2d
# A adalah ruas kiri sistem persamaan linear
# b adalah ruas kanan sistem persamaan linear

A = np.array([[2, 1, 1], [1, 4, 2], [1, 3, 9]])
b = np.array([[2], [1], [1]])
x = ls.solve(A, b)                  # mencari nilai x, y, z

print(x)

[[1.]
 [0.]
 [0.]]


### **Bentuk kodingan 3**
#### **sympy.solve**

In [34]:
# mengubah tipe data A yaitu array 2d menjadi sympy matrix
# A2 adalah ruas kiri sistem persamaan linear
# b2 adalah ruas kanan sistem persamaan linear
A2 = sp.Matrix(A)
b2 = sp.Matrix(b)
x2 = A2.solve(b2)   # mencari penyelesaian
print(x2)

Matrix([[1], [0], [0]])


### **Soal 3 dengan metode eliminasi GAUSS**

$a+b+4d =1$

$2a-b+5c =3$

$5a+2b+c+2d=2$

$-3a+2c+6d=-1$

In [35]:
# menngetikan koefisien-koefisien sistem persamaan linear dalam list 2d
# kemudian mengubahnya tipe datanya menjadi array 2d
# A adalah ruas kiri sistem persamaan linear
# b adalah ruas kanan sistem persamaan linear

A = np.array([[1, 1,0, 4], [2, -1, 5,0], [5, 2, 1, 2], [-3,0, 2, 6]])
b = np.array([[1, 3, 2, -1]])

In [36]:
# menyisipkan matrix b di kolom ke 5 matrix A
A = np.insert(A, 4, b, axis=1)
print(A)

[[ 1  1  0  4  1]
 [ 2 -1  5  0  3]
 [ 5  2  1  2  2]
 [-3  0  2  6 -1]]


In [37]:
# b2 - 2 b1
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 2 nya adalah 2 kali baris ke 1 matriks A
A = A - 2 * get_row(A, 0, 1)
print(A)

[[ 1.  1.  0.  4.  1.]
 [ 0. -3.  5. -8.  1.]
 [ 5.  2.  1.  2.  2.]
 [-3.  0.  2.  6. -1.]]


In [38]:
# b4 + 3 b1
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 4 nya adalah 3 kali baris ke 1 matriks A
A = A + 3 * get_row(A, 0, 3)
print(A)

[[ 1.  1.  0.  4.  1.]
 [ 0. -3.  5. -8.  1.]
 [ 5.  2.  1.  2.  2.]
 [ 0.  3.  2. 18.  2.]]


In [39]:
# b3 - 5 b1
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 3 nya adalah 5 kali baris ke 1 matriks A
A = A - 5 * get_row(A, 0, 2)
print(A)

[[  1.   1.   0.   4.   1.]
 [  0.  -3.   5.  -8.   1.]
 [  0.  -3.   1. -18.  -3.]
 [  0.   3.   2.  18.   2.]]


In [40]:
# b3 - b2
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 3 nya adalah baris ke 2 matriks A
A = A - get_row(A, 1, 2)
print(A)

[[  1.   1.   0.   4.   1.]
 [  0.  -3.   5.  -8.   1.]
 [  0.   0.  -4. -10.  -4.]
 [  0.   3.   2.  18.   2.]]


In [41]:
# b4 + b2
# menjumlahkan matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 4 nya adalah baris ke 2 matriks A
A = A + get_row(A, 1, 3)
print(A)

[[  1.   1.   0.   4.   1.]
 [  0.  -3.   5.  -8.   1.]
 [  0.   0.  -4. -10.  -4.]
 [  0.   0.   7.  10.   3.]]


In [42]:
# b4 + (7/4) b3
# menjumlahkan matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 4 nya adalah 7/4 kali baris ke 3 matriks A
A = A + 7/4 * get_row(A, 2, 3)
print(A)

[[  1.    1.    0.    4.    1. ]
 [  0.   -3.    5.   -8.    1. ]
 [  0.    0.   -4.  -10.   -4. ]
 [  0.    0.    0.   -7.5  -4. ]]


In [43]:
# b1 + 1/3 b2
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 1 nya adalah 1/3 kali baris ke 2 matriks A
A = A + 1/3* get_row(A, 1, 0)
print(A)

[[  1.           0.           1.66666667   1.33333333   1.33333333]
 [  0.          -3.           5.          -8.           1.        ]
 [  0.           0.          -4.         -10.          -4.        ]
 [  0.           0.           0.          -7.5         -4.        ]]


In [44]:
# -1/3 b2
# mengalikan baris ke 2 matriks b2 dengan -1/3
A = scale_row(A, 1, -1/3)
print(A)

[[  1.           0.           1.66666667   1.33333333   1.33333333]
 [  0.           1.          -1.66666667   2.66666667  -0.33333333]
 [  0.           0.          -4.         -10.          -4.        ]
 [  0.           0.           0.          -7.5         -4.        ]]


### **Fungsi Pembulatan elemen**

In [45]:
# untuk membulatkan yang angka dibelakang komanya banyak jadi 3 angka aja
def pembulatan_elemen(matriks, baris, kolom):
    """membulatkan angka yang memiliki angka dibelakang komanya banyak


    Args:
        matriks (numpy.ndarray): matriks target
        baris (int): baris matriks target
        kolom (int): baris matriks target
    """
    for baris in range(0, 4):
        for kolom in range(0, 5):
            if len(str(matriks[baris, kolom])) > 4:
                matriks[baris, kolom] = round(matriks[baris, kolom], 3)     # membulatkan angka dengan 3 angka di belakang koma
    return matriks


In [46]:
# b1 + (5/3) / 4 b3
# menjumlahkan matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 1 nya adalah (5/3)*4 kali baris ke 3 matriks A
A = A + (1/4 * get_row(A, 2, 0)) * 5 / 3
print(A)

[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16 -2.83333333e+00
  -3.33333333e-01]
 [ 0.00000000e+00  1.00000000e+00 -1.66666667e+00  2.66666667e+00
  -3.33333333e-01]
 [ 0.00000000e+00  0.00000000e+00 -4.00000000e+00 -1.00000000e+01
  -4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.50000000e+00
  -4.00000000e+00]]


In [47]:
# penggil fungsi yang membulatkan semua elemen matriks yang memiliki banyak angka dibelakang koma menjadi 3 angka dibelakang koma
# 4 adalah jumlah baris, 4 adalah jumlah kolomnya
A = pembulatan_elemen(A, 4, 5)
print(A)

[[  1.      0.     -0.     -2.833  -0.333]
 [  0.      1.     -1.667   2.667  -0.333]
 [  0.      0.     -4.    -10.     -4.   ]
 [  0.      0.      0.     -7.5    -4.   ]]


In [48]:
# -1/7.5 b4
# mengalikan baris ke 4 matriks A dengan -1/7.5
A = scale_row(A, 3, -1/7.5)
print(A)

[[  1.           0.           0.          -2.833       -0.333     ]
 [  0.           1.          -1.667        2.667       -0.333     ]
 [  0.           0.          -4.         -10.          -4.        ]
 [  0.           0.           0.           1.           0.53333333]]


In [49]:
# b1 + 17/6 b4
# menjumlahkan matriks A dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 1 nya adalah 17/6 kali baris ke 4 matriks A
# round itu untuk membulatkan angka yang komanya banyak jadi 3 angka saja
A = A + round(17/6, 3) * get_row(A, 3, 0)
print(A)

[[  1.           0.           0.           0.           1.17793333]
 [  0.           1.          -1.667        2.667       -0.333     ]
 [  0.           0.          -4.         -10.          -4.        ]
 [  0.           0.           0.           1.           0.53333333]]


In [50]:
# penggil fungsi yang membulatkan semua elemen matriks yang memiliki banyak angka dibelakang koma menjadi 3 angka dibelakang koma
# 4 adalah jumlah baris, 4 adalah jumlah kolomnya
A = pembulatan_elemen(A, 4, 5)
print(A)

[[  1.      0.      0.      0.      1.178]
 [  0.      1.     -1.667   2.667  -0.333]
 [  0.      0.     -4.    -10.     -4.   ]
 [  0.      0.      0.      1.      0.533]]


In [51]:
# b2 - (5/3) / 4 b3
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 2 nya adalah (5/3)/4 kali baris ke 3 matriks A
A = A - 1/4 * get_row(A, 2, 1) * round(5 / 3, 3)
print(A)

[[  1.       0.       0.       0.       1.178 ]
 [  0.       1.       0.       6.8345   1.334 ]
 [  0.       0.      -4.     -10.      -4.    ]
 [  0.       0.       0.       1.       0.533 ]]


In [52]:
# b2 - 6.8345 * b4
# round(8 / 3, 3) + 1 / 4 * 10 * round(5 / 3, 3) = 6.8345
# mengurangi matriks A dengan matriks yang dihasilkan oelh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 2 nya adalah 6.8345 kali baris ke 1 matriks A
A = A - get_row(A, 3, 1) * (round(8 / 3, 3) + 1 / 4 * 10 * round(5 / 3, 3))
print(A)

[[  1.          0.          0.          0.          1.178    ]
 [  0.          1.          0.          0.         -2.3087885]
 [  0.          0.         -4.        -10.         -4.       ]
 [  0.          0.          0.          1.          0.533    ]]


In [53]:
# -1/4 b3
# mengalikan baris ke 3 dengan -1/4
A = scale_row(A, 2, -1/4)
print(A)

[[ 1.         0.         0.         0.         1.178    ]
 [ 0.         1.         0.         0.        -2.3087885]
 [ 0.         0.         1.         2.5        1.       ]
 [ 0.         0.         0.         1.         0.533    ]]


In [54]:
# b3 - 5/2 b4
# mengurangi matriks A dengan matriks yang dihasilkan oleh fungsi get_row
# matriks yang dihasilkan tersebut adalah matriks nol yang baris ke 3 nya adalah 5/2 kali baris ke 4 matriks A
A = A - 5/2 * get_row(A, 3, 2)
print(A)

[[ 1.         0.         0.         0.         1.178    ]
 [ 0.         1.         0.         0.        -2.3087885]
 [ 0.         0.         1.         0.        -0.3325   ]
 [ 0.         0.         0.         1.         0.533    ]]


In [55]:
# modul yang convert dari float ke pecahan
from fractions import Fraction

In [56]:
# menyimpan masing-masing hasilnya di a,b,c,d
a = A[0, 4]
b = A[1, 4]
c = A[2, 4]
d = A[3, 4]

print("Hasil dari Operasi diatas adalah")

print(f'a = {Fraction(a).limit_denominator(50)}')
print(f'b = {Fraction(b).limit_denominator(60)}')
print(f'c = {Fraction(c).limit_denominator(50)}')
print(f'd = {Fraction(d).limit_denominator(50)}')


Hasil dari Operasi diatas adalah
a = 53/45
b = -127/55
c = -1/3
d = 8/15


### **solusi dengan sympy**

In [57]:
# menngetikan koefisien-koefisien sistem persamaan linear dalam list 2d
# kemudian mengubahnya tipe datanya menjadi array 2d
# matriks A adalah koefisien yang ada di ruas kiri
# matriks b adalah hasil yang ada di ruas kanan
A = np.array([[1, 1, 0, 4], [2, -1, 5, 0], [5, 2, 1, 2], [-3, 0, 2, 6]])
b = np.array([[1], [3], [2], [-1]])

In [58]:
# mengubah tipe data numpy.ndarray jadi sympy matrix
A2 = sp.Matrix(A)
b2 = sp.Matrix(b)
x2 = A2.solve(b2)       # mencari solusi
print(x2)

Matrix([[53/45], [-104/45], [-1/3], [8/15]])
